In [2]:
import pybedtools
import pandas as pd
import csv

In [3]:
track=pybedtools.BedTool('Example.gff')
ref=pybedtools.BedTool('gencode.v28.annotation.gtf')
gene = track.intersect(ref, wb=True)
txtfile = gene.moveto('intersected.txt')

/Users/debapriyasinha/opt/anaconda3/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)

In [4]:
df=pd.read_csv('intersected.txt', names=['ref1', 'source1', 'method1', 'start1', 'stop1', 'score1', 'strand1', 'phase1', 'group1', 'ref2', 'source2', 'feature', 'start2', 'stop2', 'score2','strand2', 'frame', 'attribute'], sep='\t')
df.head()
reqdf=df[['ref1','start1','stop1','score1','strand2','attribute']]
reqdf.rename(columns={'ref1':'ref','start1':'start','stop1':'stop','score1':'score','strand2':'strand'}, inplace=True)
reqdf.head()
#[['ref','start','stop','score','strand','attribute']]
#gene_type "protein_coding"

/Users/debapriyasinha/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4125: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,ref,start,stop,score,strand,attribute
0,chr1,961771,962449,3.54,+,"gene_id ""ENSG00000187961.13""; gene_type ""prote..."
1,chr1,961771,962449,3.54,+,"gene_id ""ENSG00000187961.13""; transcript_id ""E..."
2,chr1,961826,962047,3.54,+,"gene_id ""ENSG00000187961.13""; transcript_id ""E..."
3,chr1,961826,962047,3.54,+,"gene_id ""ENSG00000187961.13""; transcript_id ""E..."
4,chr1,962355,962449,3.54,+,"gene_id ""ENSG00000187961.13""; transcript_id ""E..."

In [5]:
#select the rows that contains the string 'gene_type "protein_coding"'
reqdf = reqdf[reqdf['attribute'].str.contains('gene_type "protein_coding"')]
#split the string attribute into columns
reqdf = reqdf.join(reqdf['attribute'].str.split(';', expand=True))
reqdf = reqdf.drop('attribute', 1)

reqdf.head(20)

,ref,start,stop,score,strand,0,1,2,3,4,...,11,12,13,14,15,16,17,18,19,20
0,chr1,961771,962449,3.54,+,"gene_id ""ENSG00000187961.13""","gene_type ""protein_coding""","gene_name ""KLHL17""",level 2,"havana_gene ""OTTHUMG00000040721.6""",...,None,None,None,None,None,None,None,None,None,None
1,chr1,961771,962449,3.54,+,"gene_id ""ENSG00000187961.13""","transcript_id ""ENST00000338591.7""","gene_type ""protein_coding""","gene_name ""KLHL17""","transcript_type ""protein_coding""",...,"tag ""CCDS""","ccdsid ""CCDS30550.1""","havana_gene ""OTTHUMG00000040721.6""","havana_transcript ""OTTHUMT00000097875.3""",,None,None,None,None,None
2,chr1,961826,962047,3.54,+,"gene_id ""ENSG00000187961.13""","transcript_id ""ENST00000338591.7""","gene_type ""protein_coding""","gene_name ""KLHL17""","transcript_type ""protein_coding""",...,"tag ""basic""","tag ""appris_principal_1""","tag ""CCDS""","ccdsid ""CCDS30550.1""","havana_gene ""OTTHUMG00000040721.6""","havana_transcript ""OTTHUMT00000097875.3""",,None,None,None
3,chr1,961826,962047,3.54,+,"gene_id ""ENSG00000187961.13""","transcript_id ""ENST00000338591.7""","gene_type ""protein_coding""","gene_name ""KLHL17""","transcript_type ""protein_coding""",...,"tag ""basic""","tag ""appris_principal_1""","tag ""CCDS""","ccdsid ""CCDS30550.1""","havana_gene ""OTTHUMG00000040721.6""","havana_transcript ""OTTHUMT00000097875.3""",,None,None,None
4,chr1,962355,962449,3.54,+,"gene_id ""ENSG00000187961.13""","transcript_id ""ENST00000338591.7""","gene_type ""protein_coding""","gene_name ""KLHL17""","transcript_type ""protein_coding""",...,"tag ""basic""","tag ""appris_principal_1""","tag ""CCDS""","ccdsid ""CCDS30550.1""","havana_gene ""OTTHUMG00000040721.6""","havana_transcript ""OTTHUMT00000097875.3""",,None,None,None
5,chr1,962355,962449,3.54,+,"gene_id ""ENSG00000187961.13""","transcript_id ""ENST00000338591.7""","gene_type ""protein_coding""","gene_name ""KLHL17""","transcript_type ""protein_coding""",...,"tag ""basic""","tag ""appris_principal_1""","tag ""CCDS""","ccdsid ""CCDS30550.1""","havana_gene ""OTTHUMG00000040721.6""","havana_transcript ""OTTHUMT00000097875.3""",,None,None,None
6,chr1,961771,962449,3.54,+,"gene_id ""ENSG00000187961.13""","transcript_id ""ENST00000622660.1""","gene_type ""protein_coding""","gene_name ""KLHL17""","transcript_type ""protein_coding""",...,,None,None,None,None,None,None,None,None,None
7,chr1,962082,962449,3.54,+,"gene_id ""ENSG00000187961.13""","transcript_id ""ENST00000622660.1""","gene_type ""protein_coding""","gene_name ""KLHL17""","transcript_type ""protein_coding""",...,"tag ""basic""","havana_gene ""OTTHUMG00000040721.6""",,None,None,None,None,None,None,None
8,chr1,962082,962449,3.54,+,"gene_id ""ENSG00000187961.13""","transcript_id ""ENST00000622660.1""","gene_type ""protein_coding""","gene_name ""KLHL17""","transcript_type ""protein_coding""",...,"tag ""basic""","havana_gene ""OTTHUMG00000040721.6""",,None,None,None,None,None,None,None
9,chr1,961771,962449,3.54,+,"gene_id ""ENSG00000187961.13""","transcript_id ""ENST00000463212.1""","gene_type ""protein_coding""","gene_name ""KLHL17""","transcript_type ""retained_intron""",...,None,None,None,None,None,None,None,None,None,None
10,chr1,961826,962449,3.54,+,"gene_id ""ENSG00000187961.13""","transcript_id ""ENST00000463212.1""","gene_type ""protein_coding""","gene_name ""KLHL17""","transcript_type ""retained_intron""",...,"havana_transcript ""OTTHUMT00000097877.1""",,None,None,None,None,None,None,None,None
11,chr1,1012424,1012804,1.05,+,"gene_id ""ENSG00000187608.8""","gene_type ""protein_coding""","gene_name ""ISG15""",level 2,"havana_gene ""OTTHUMG00000040777.3""",...,None,None,None,None,None,None,None,None,None,None
12,chr1,1012424,1012804,1.05,+,"gene_id ""ENSG00000187608.8""","transcript_id ""ENST00000624697.3""","gene_type ""protein_coding""","gene_name ""ISG15""","transcript_type ""protein_coding""",...,"havana_gene ""OTTHUMG00000040777.3""","havana_transcript ""OTTHUMT00000479384.1""",,None,None,None,None,None,None,None
13,chr1,1012424,1012804,1.05,+,"gene_id ""ENSG00000187608.8""","transcript_id ""ENST00000624652.1""","gene_type ""protein_coding""","gene_name ""ISG15""","transcript_type ""protein_coding""",...,"havana_gene ""OTTHUMG00000040777.3""","havana_transcript ""OTTHUMT00000479385.2""",,None,None,None,None,None,None,None
16,chr1,1231002,1231015,4.09,-,"gene_id ""ENSG00000078808.16""","gene_type ""protein_coding""","gene_name ""SDF4""",level 2,"havana_gene ""OTTHUMG00000001812.6""",...,None,None,None,None,None,None,None,None,None,None
17,chr1,1231002,1231015,4.09,-,"gene_id ""ENSG00000078808.16""","transcript_id ""ENST00000360001.10""","gene_type ""protein_coding""","gene_name ""SDF4""","transcript_type ""protein_coding""",...,"tag ""CCDS""","ccdsid ""CCDS30553.1""","havana_gene ""OTTHUMG00000001812.6""","havana_transcript ""OTTHUMT00000005064.1""",,None,None,None,None,None
18,chr1,1231002,1231015,4.09,-,"gene_id ""ENSG00000078808.16""","transcript_id ""ENST00000465727.5""","gene_type ""protein_coding""","gene_name ""SDF4""","transcript_type ""nonsense_mediated_decay""",...,,None,None,None,None,None,None,None,None,None
19,chr1,1231002,1231015,4.09,-,"gene_id ""ENSG00000078808.16""","transcript_id ""ENST00000263741.11""","gene_type ""protein_coding""","gene_name ""SDF4""","transcript_type ""protein_coding""",...,"tag ""CCDS""","ccdsid ""CCDS12.1""","havana_gene ""OTTHUMG00000001812.6""","havana_transcript ""OTTHUMT00000005070.1""",,None,None,None,None,None
20,chr1,1231002,1231015,4.09,-,"gene_id ""ENSG00000078808.16""","transcript_id ""ENST00000459994.2""","gene_type ""protein_coding""","gene_name ""SDF4""","transcript_type ""processed_transcript""",...,,None,None,None,None,None,None,None,None,None
21,chr1,1246514,1246571,0.22,-,"gene_id ""ENSG00000184163.3""","transcript_id ""ENST00000330388.2""","gene_type ""protein_coding""","gene_name ""C1QTNF12""","transcript_type ""protein_coding""",...,"tag ""basic""","tag ""appris_principal_1""","tag ""CCDS""","ccdsid ""CCDS30554.1""","havana_gene ""OTTHUMG00000001412.6""","havana_transcript ""OTTHUMT00000004080.4""",,None,None,None

In [6]:
#select the column that contains string "gene_name"
list(reqdf.columns)
selected_cols = list(range(0, 21))
#reqdf[selected_cols]
newdf=reqdf[reqdf[selected_cols].apply(lambda x: x.str.contains('gene_name'))]
newdf[2].update(newdf.pop(3))
newdf.isnull().sum()
newdf.head(25)
#newdf=newdf.drop.isnull()
#newdf.head(30)
#reqdf[reqdf.select_dtypes(include='object').apply(lambda x: x.str.contains('gene_name "SDF4"')).all(axis=1)]

,ref,start,stop,score,strand,0,1,2,4,5,...,11,12,13,14,15,16,17,18,19,20
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""KLHL17""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""KLHL17""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""KLHL17""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""KLHL17""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""KLHL17""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""KLHL17""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""KLHL17""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""KLHL17""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""KLHL17""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""KLHL17""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""KLHL17""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""ISG15""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""ISG15""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""ISG15""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""SDF4""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""SDF4""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""SDF4""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""SDF4""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""SDF4""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""C1QTNF12""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""C1QTNF12""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""C1QTNF12""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""C1QTNF12""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""ACAP3""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"gene_name ""ACAP3""",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
data = [reqdf["ref"], reqdf['start'], reqdf['stop'], newdf[2], reqdf['score'], reqdf['strand']]
headers = ['ref','start','stop','name','score','strand']
df3 = pd.concat(data, axis=1, keys=headers)
df3 = df3.join(df3['name'].str.split('"', expand=True))
df4 = [df3["ref"], df3['start'], df3['stop'], df3[1], df3['score'], df3['strand']]
headers = ['ref','start','stop','name','score','strand']
finaldf = pd.concat(df4, axis=1, keys=headers)
finaldf.head(20)
finaldf.to_csv('output.bed', sep='\t', index=False)
finaldf.to_csv('output.bed', sep='\t', quoting=csv.QUOTE_NONE, escapechar='"', index=False)
#cant use bedtools merge since that will unify many separate peaks

In [8]:
finaldf.head(25)

     ref    start     stop      name  score strand
0   chr1   961771   962449    KLHL17   3.54      +
1   chr1   961771   962449    KLHL17   3.54      +
2   chr1   961826   962047    KLHL17   3.54      +
3   chr1   961826   962047    KLHL17   3.54      +
4   chr1   962355   962449    KLHL17   3.54      +
5   chr1   962355   962449    KLHL17   3.54      +
6   chr1   961771   962449    KLHL17   3.54      +
7   chr1   962082   962449    KLHL17   3.54      +
8   chr1   962082   962449    KLHL17   3.54      +
9   chr1   961771   962449    KLHL17   3.54      +
10  chr1   961826   962449    KLHL17   3.54      +
11  chr1  1012424  1012804     ISG15   1.05      +
12  chr1  1012424  1012804     ISG15   1.05      +
13  chr1  1012424  1012804     ISG15   1.05      +
16  chr1  1231002  1231015      SDF4   4.09      -
17  chr1  1231002  1231015      SDF4   4.09      -
18  chr1  1231002  1231015      SDF4   4.09      -
19  chr1  1231002  1231015      SDF4   4.09      -
20  chr1  1231002  1231015      SDF4   4.09      -
21  chr1  1246514  1246571  C1QTNF12   0.22      -
22  chr1  1246514  1246571  C1QTNF12   0.22      -
23  chr1  1245723  1246571  C1QTNF12   0.22      -
24  chr1  1245723  1246571  C1QTNF12   0.22      -
27  chr1  1298567  1298679     ACAP3   0.26      -
28  chr1  1298567  1298679     ACAP3   0.26      -

In [9]:
combdf = finaldf.groupby(['name','score']).agg({'start':'min', 'stop':'max'}).reset_index()
combdf.head(20)

        name  score      start       stop
0      ACAP3   0.26    1297956    1298958
1      ACAP3   1.40    1309345    1309567
2      ACAP3   1.55    1302261    1304260
3      ACBD3   0.18  226186066  226186730
4     ACOT11   1.02   54622952   54624556
5     ADARB2   0.69    1736593    1737476
6    ADIPOR1   0.96  202957647  202958572
7    AFAP1L2   0.41  114403486  114404756
8     AHCTF1   1.12  246930425  246931978
9        AK2   1.70   33080114   33080996
10       AK4   1.16   65147549   65148632
11     ALG14   3.96   95071946   95072945
12      ALPL   2.57   21509372   21510372
13     AMY2A   3.70  103616811  103617114
14      ANK3   1.08   60140222   60140639
15     ANXA7   3.20   73413068   73413068
16     AQP10   1.61  154324554  154325325
17  ARHGAP21   2.46   24722645   24723668
18  ARHGEF19   0.89   16206324   16208011
19    ARID4B   1.73  235327785  235328219

In [10]:
remdata = [finaldf["ref"], finaldf['name'], finaldf['strand']]
headers = ['ref','name','strand']
remcols = pd.concat(remdata, axis=1, keys=headers)
remcols = remcols.drop_duplicates(subset='name', keep="first")
remcols.head()

     ref      name strand
0   chr1    KLHL17      +
11  chr1     ISG15      +
16  chr1      SDF4      -
21  chr1  C1QTNF12      -
27  chr1     ACAP3      -

In [11]:
finalcomb = pd.merge(combdf,remcols,how = "inner", on = "name")
finalcomb.head(20)

        name  score      start       stop    ref strand
0      ACAP3   0.26    1297956    1298958   chr1      -
1      ACAP3   1.40    1309345    1309567   chr1      -
2      ACAP3   1.55    1302261    1304260   chr1      -
3      ACBD3   0.18  226186066  226186730   chr1      -
4     ACOT11   1.02   54622952   54624556   chr1      +
5     ADARB2   0.69    1736593    1737476  chr10      -
6    ADIPOR1   0.96  202957647  202958572   chr1      -
7    AFAP1L2   0.41  114403486  114404756  chr10      -
8     AHCTF1   1.12  246930425  246931978   chr1      -
9        AK2   1.70   33080114   33080996   chr1      -
10       AK4   1.16   65147549   65148632   chr1      +
11     ALG14   3.96   95071946   95072945   chr1      -
12      ALPL   2.57   21509372   21510372   chr1      +
13     AMY2A   3.70  103616811  103617114   chr1      +
14      ANK3   1.08   60140222   60140639  chr10      -
15     ANXA7   3.20   73413068   73413068  chr10      -
16     AQP10   1.61  154324554  154325325   chr1      +
17  ARHGAP21   2.46   24722645   24723668  chr10      -
18  ARHGEF19   0.89   16206324   16208011   chr1      -
19    ARID4B   1.73  235327785  235328219   chr1      -

In [12]:
data = [finalcomb["ref"], finalcomb['start'], finalcomb['stop'], finalcomb['name'], finalcomb['score'], finalcomb['strand']]
#headers = ['ref','start','stop','name','score','strand']
foroutput = pd.concat(data, axis=1)
foroutput.head(20)
foroutput = foroutput.rename(columns=foroutput.iloc[0]).drop(foroutput.index[0])
foroutput.to_csv('afterfiltration.bed', sep='\t')
foroutput.to_csv('afterfiltration.bed', sep='\t', quoting=csv.QUOTE_NONE, escapechar='"', index=False)

In [13]:
a=pybedtools.BedTool('afterfiltration.bed').sort()
a.moveto('afterfiltration_sorted.bed')
#tosort=a.sort()

/Users/debapriyasinha/opt/anaconda3/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)